// client/src/app/common/partials/footer/footer.component.ts
import { Component } from '@angular/core'
import { CopyButtonComponent } from '../../../modules/website/pages/home/elements/onboarding-showcase/copy-to-clipboard.component'
import { WaitingListFormComponent } from '../waiting-list-form/waiting-list-form.component'

@Component({
  selector: 'app-footer',
  imports: [WaitingListFormComponent, CopyButtonComponent],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss'
})
export class FooterComponent {}

<div>
  <div class="container-fluid has-background-white is-relative is-bottom-cta">
    <div class="has-background-wheel"></div>
    <div class="container py-7">
      <div class="columns is-multiline">
        <div class="column is-8 is-offset-2">
          <div class="content is-normal has-text-centered">
            <img
              src="./assets/images/logo-peacock.svg"
              width="64"
              height="98"
              alt="Manifest logo"
            />
            <h3 class="title is-3 mt-4">Start building with Manifest</h3>
            <p>Need to setup a backend in minutes? Start now!</p>
          </div>
        </div>
        <div class="column is-6-tablet is-offset-3">
          <div
            class="content is-normal is-flex is-align-items-center is-justify-content-center box-main-cta is-flex-direction-column"
          >
            <app-copy-button></app-copy-button>
            <div
              class="content is-normal mb-5 is-flex is-align-items-center is-justify-content-center box-main-cta"
            >
              <a
                class="button is-dark is-small"
                href="/docs/install"
                target="_blank"
              >
                <span>Get started</span>
              </a>
              <a
                class="button is-white is-small"
                href="https://github.com/mnfst/manifest"
                target="_blank"
              >
                <span class="icon">
                  <i class="fa fa-star has-text-warning"></i>
                </span>
                <span>Give a star</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer
    class="footer has-background-white-bis has-text-dark pb-4 has-border-top"
  >
    <div class="container">
      <div>
        <div class="columns is-multiline">
          <div class="column is-3">
            <div class="content">
              <p class="has-text-weight-bold is-size-6">resources</p>
              <ul class="no-lst">
                <li>
                  <a href="https://manifest.build/docs" target="_blank">
                    Developer Docs
                  </a>
                </li>
                <li>
                  <a
                    href="https://github.com/mnfst/manifest/blob/master/CONTRIBUTING.md"
                    target="_blank"
                  >
                    Contributor Docs
                  </a>
                </li>
                <li>
                  <a href="/faq">FAQ</a>
                </li>
              </ul>
            </div>
          </div>

          <div class="column is-3">
            <div class="content">
              <p class="has-text-weight-bold is-size-6">Community</p>
              <ul class="no-lst">
                <li>
                  <span class="icon-text">
                    <span class="icon">
                      <i class="fab fa-github is-size-6"></i>
                    </span>
                    <a href="https://github.com/mnfst/manifest" target="_blank">
                      GitHub
                    </a>
                  </span>
                </li>
                <li>
                  <span class="icon-text">
                    <span class="icon">
                      <i class="fab fa-discord is-size-6"></i>
                    </span>
                    <a href="https://discord.gg/FepAked3W7" target="_blank">
                      Discord
                    </a>
                  </span>
                </li>
                <li>
                  <span class="icon-text">
                    <span class="icon">
                      <i class="fa-regular fa-comments is-size-6"></i>
                    </span>
                    <a
                      href="https://github.com/mnfst/manifest/discussions"
                      target="_blank"
                      width="64"
                      height="98"
                    >
                      Discussions
                    </a>
                  </span>
                </li>
                <li>
                  <span class="icon-text">
                    <span class="icon">
                      <i class="fa-regular fa-heart is-size-6"></i>
                    </span>
                    <a href="/sponsors">Sponsor Manifest</a>
                  </span>
                </li>
              </ul>
            </div>
          </div>
          <div class="column is-3">
            <div class="content">
              <p class="has-text-weight-bold is-size-6">More</p>
              <ul class="no-lst">
                <li>
                  <span class="icon-text">
                    <span class="icon">
                      <i class="fa-solid fa-plug is-size-6"></i>
                    </span>
                    <a href="/integrations">Integrations</a>
                  </span>
                </li>
                <li>
                  <span class="icon-text">
                    <span class="icon">
                      <i class="fa-regular fa-image is-size-6"></i>
                    </span>
                    <a href="/brand-assets">Brand assets</a>
                  </span>
                </li>
                <li>
                  <span class="icon-text">
                    <span class="icon">
                      <i class="fa-regular fa-handshake is-size-6"></i>
                    </span>
                    <a href="/partnerships">Partner with us</a>
                  </span>
                </li>
              </ul>
            </div>
          </div>
          <div class="column is-3">
            <div class="content">
              <p class="has-text-weight-bold is-size-6">Manifest Cloud</p>
              <p>Subscribe to the waitlist to know when it is out.</p>
              <app-waiting-list-form></app-waiting-list-form>
            </div>
          </div>
          <div class="column is-12">
            <div class="separator"></div>
          </div>
          <div class="column is-6">
            <img
              src="./assets/images/logo-transparent.svg"
              width="180"
              height="50"
              alt="logo of manifest"
              class="footer-logo"
              loading="lazy"
            />
          </div>
          <div
            class="column is-6 has-text-right is-align-items-center is-flex is-justify-content-flex-end"
          >
            <a class="is-underlined" href="/privacy"> Privacy policy </a>
            <span class="mx-4 has-text-grey-lighter">•</span>
            <span>
              Source code licensed
              <a
                class="is-underlined"
                href="https://opensource.org/license/mit"
                target="_blank"
              >
                MIT
              </a>
            </span>
          </div>
        </div>
      </div>
    </div>
  </footer>
</div>

// src/app/components/layout/Footer.tsx
import Image from 'next/image'
import React from 'react'
import SubscribeForm from '../SubscribeForm'
import InstallCLI from './../InstallCLI'

const Footer: React.FC = () => {
  return (
    <div>
      <div className="container-fluid has-background-white is-relative is-bottom-cta">
        <div className="has-background-wheel"></div>
        <div className="container py-7">
          <div className="columns is-multiline">
            <div className="column is-8 is-offset-2">
              <div className="content is-normal has-text-centered">
                <Image
                  src="./assets/images/logo-peacock.svg"
                  width={64}
                  height={98}
                  alt="Manifest logo"
                />
                <h3 className="title is-3 mt-4">
                  Start building with Manifest
                </h3>
                <p>
                  Your frontend needs a backend? Set it up in minutes and you’re
                  good to go!
                </p>
              </div>
            </div>
            <div className="column is-6-tablet is-offset-3">
              <div className="content is-normal  is-flex is-align-items-center is-justify-content-center box-main-cta is-flex-direction-column">
                <InstallCLI />
                <div className="content is-normal  mb-5 is-flex is-align-items-center is-justify-content-center box-main-cta">
                  <a
                    className="button is-white is-small"
                    href="/docs/install"
                    target="_blank"
                  >
                    <span className="icon">
                      <i className="far fa-file-lines"></i>
                    </span>
                    <span>Documentation</span>
                  </a>
                  <a
                    className="button is-white is-small"
                    href="https://github.com/mnfst/manifest"
                    target="_blank"
                  >
                    <span className="icon">
                      <i className="fab fa-github"></i>
                    </span>
                    <span> Github</span>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <footer className="footer has-background-white-bis has-text-dark pb-4 has-border-top">
        <div className="container">
          <div>
            <div className="columns is-multiline">
              <div className="column is-3">
                <div className="content">
                  <p className="has-text-weight-bold is-size-6">Docs</p>
                  <ul className="no-lst">
                    <li>
                      <a href="https://manifest.build/docs" target="_blank">
                        Developer Docs
                      </a>
                    </li>
                    <li>
                      <a
                        href="https://github.com/mnfst/manifest/blob/master/CONTRIBUTING.md"
                        target="_blank"
                      >
                        Contributor Docs
                      </a>
                    </li>
                  </ul>
                </div>
              </div>

              <div className="column is-3">
                <div className="content">
                  <p className="has-text-weight-bold is-size-6">Community</p>
                  <ul className="no-lst">
                    <li>
                      <span className="icon-text">
                        <span className="icon">
                          <i className="lni lni-github-original is-size-6"></i>
                        </span>
                        <a
                          href="https://github.com/mnfst/manifest"
                          target="_blank"
                        >
                          Github
                        </a>
                      </span>
                    </li>
                    <li>
                      <span className="icon-text">
                        <span className="icon">
                          <i className="lni lni-discord-alt is-size-6"></i>
                        </span>
                        <a href="https://discord.gg/FepAked3W7" target="_blank">
                          {' '}
                          Discord
                        </a>
                      </span>
                    </li>
                    <li>
                      <span className="icon-text">
                        <span className="icon">
                          <i className="lni lni-comments-alt-2 is-size-6"></i>
                        </span>
                        <a
                          href="https://github.com/mnfst/manifest/discussions"
                          target="_blank"
                        >
                          Discussions
                        </a>
                      </span>
                    </li>
                    <li>
                      <span className="icon-text">
                        <span className="icon">
                          <i className="lni lni-heart-fill is-size-6"></i>
                        </span>
                        <a href="/sponsors">Sponsor Manifest</a>
                      </span>
                    </li>
                  </ul>
                </div>
              </div>
              <div className="column is-3">
                <div className="content">
                  <p className="has-text-weight-bold is-size-6">More</p>
                  <ul className="no-lst">
                    <li>
                      <span className="icon-text">
                        <span className="icon">
                          <i className="lni lni-plug is-size-6"></i>
                        </span>
                        <a href="/integrations">Integrations</a>
                      </span>
                    </li>
                    <li>
                      <span className="icon-text">
                        <span className="icon">
                          <i className="lni lni-image is-size-6"></i>
                        </span>
                        <a href="/brand-assets">Brand assets</a>
                      </span>
                    </li>
                    <li>
                      <span className="icon-text">
                        <span className="icon">
                          <i className="lni lni-handshake is-size-6"></i>
                        </span>
                        <a href="/partnerships">Partner with us</a>
                      </span>
                    </li>
                  </ul>
                </div>
              </div>
              <div className="column is-3">
                <div className="content">
                  <p className="has-text-weight-bold is-size-6">
                    1-click deploy
                  </p>
                  <p>Join the waitlist</p>
                  <SubscribeForm />
                </div>
              </div>
              <div className="column is-12">
                <div className="separator"></div>
              </div>
              <div className="column is-6">
                <Image
                  src="./assets/images/logo-transparent.svg"
                  width={180}
                  height={50}
                  alt="logo of manifest"
                  className="footer-logo"
                  loading="lazy"
                />
              </div>
              <div className="column is-6 has-text-right is-align-items-center is-flex is-justify-content-flex-end">
                <a className=" is-underlined" href="/privacy">
                  Privacy policy
                </a>
                <span className="mx-4 has-text-grey-lighter">•</span>
                <span>
                  Source code licensed{' '}
                  <a
                    className=" is-underlined"
                    href="https://opensource.org/license/mit"
                    target="_blank"
                  >
                    MIT
                  </a>
                </span>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

export default Footer
