// client/src/app/common/partials/header/header.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent {}

<!-- Header -->
<nav
  class="navbar has-background-glass is-fixed-top"
  role="navigation"
  aria-label="main navigation"
>
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <img
          src="/assets/images/logo-poc.svg"
          width="198"
          height="40.53"
          alt="logo of manifest"
          loading="lazy"
          class="mx-2"
        />
      </a>
      <div class="is-flex">
        <a
          class="navbar-item px- 5-tablet is-hidden-desktop"
          href="https://discord.gg/FepAked3W7"
          target="_blank"
        >
          <i class="fab fa-discord is-size-6"></i>
        </a>
        <a
          class="navbar-item px-5-tablet is-hidden-desktop"
          href="https://manifest.build/docs/"
          target="_blank"
        >
          <i class="fa fa-file-lines is-size-6"></i>
        </a>
      </div>
    </div>

    <div class="navbar-menu has-text-weight-bold">
      <div class="navbar-end">
        <a
          class="navbar-item"
          href="https://discord.gg/FepAked3W7"
          target="_blank"
        >
          <i class="fab fa-discord is-size-6"></i>
        </a>
        <div class="navbar-item pt-4">
          <!-- Place this tag where you want the button to render. -->
          <!-- Place this tag where you want the button to render. -->
          <!-- <a
            class="github-button"
            href="https://github.com/mnfst/manifest"
            data-color-scheme="no-preference: light; light: light; dark: dark;"
            data-size="large"
            data-show-count="true"
            aria-label="Star mnfst/manifest on GitHub"
            >Star</a
          > -->
        </div>
        <div class="navbar-item">
          <a
            class="button is-small is-dark"
            href="mailto:sebastien@manifest.build"
            target="_blank"
          >
            Contact us
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

// src/app/components/layout/Header.tsx
// components/Header.js

const Header = () => {
  return (
    <nav
      className="navbar has-background-glass is-fixed-top"
      role="navigation"
      aria-label="main navigation"
    >
      <div className="container">
        <div className="navbar-brand">
          <a className="navbar-item" href="/">
            <img
              src="/assets/images/logo-poc.svg"
              width={198}
              alt="logo of manifest"
              loading="lazy"
              className="mx-2"
            />
          </a>
          <div className="is-flex">
            <a className="navbar-item px-5-tablet" href="/docs" target="_blank">
              <span className="is-hidden-touch">Documentation</span>
              <i className="lni lni-empty-file is-size-6 is-hidden-desktop"></i>
            </a>
            <a
              className="navbar-item px-5-tablet is-hidden-desktop"
              href="https://discord.gg/FepAked3W7"
              target="_blank"
            >
              <i className="lni lni-discord-alt is-size-6"></i>
            </a>
            <a
              className="navbar-item px-5-tablet is-hidden-desktop"
              href="https://github.com/mnfst/manifest"
              target="_blank"
            >
              <i className="lni lni-github-original is-size-6"></i>
            </a>
          </div>
        </div>

        <div className="navbar-menu has-text-weight-bold">
          <div className="navbar-end">
            <a
              className="navbar-item"
              href="https://discord.gg/FepAked3W7"
              target="_blank"
            >
              <i className="lni lni-discord-alt is-size-6"></i>
            </a>
            <a
              className="navbar-item"
              href="https://github.com/mnfst/manifest"
              target="_blank"
            >
              <i className="lni lni-github-original is-size-6"></i>
            </a>
            <div className="navbar-item">
              <a
                className="button is-small is-link"
                href="/docs/install"
                target="_blank"
              >
                Get started
              </a>
            </div>
          </div>
        </div>
      </div>
    </nav>
  )
}

export default Header
