// src/app/partials/header/header.component.ts
import { Component, OnInit } from '@angular/core'
import { NavigationEnd, Router } from '@angular/router'

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  currentPath: string

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.router.events.subscribe((routeChanged) => {
      if (routeChanged instanceof NavigationEnd) {
        this.currentPath = routeChanged.url
      }
    })
  }
}

<nav class="navbar is-white">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" routerLink="/">
        <img src="./assets/images/logo-black.svg" alt="CASE logo" width="124" />
        <span class="beta has-text-weight-bold ml-1">beta</span>
      </a>
      <div class="navbar-touch is-hidden-desktop">
        <a
          class="navbar-item px-2"
          target="_blank"
          href="https://docs.case.app"
        >
          <span class="icon-text has-text-dark">
            <span>Docs</span>
            <span class="icon">
              <i class="fa-solid fa-square-up-right ml-1"></i>
            </span>
          </span>
        </a>
        <a class="navbar-item has-text-dark px-2" routerLink="/faq">
          <span>FAQ</span>
        </a>
        <a
          class="navbar-item px-2"
          href="https://github.com/casejs/case"
          target="_blank"
        >
          <i class="has-text-dark fa-brands is-size-5 fa-github"></i>
        </a>
        <a
          class="navbar-item px-2"
          href="https://discord.com/invite/FepAked3W7"
          target="_blank"
        >
          <i class="has-text-dark fa-brands is-size-5 fa-discord"></i>
        </a>
      </div>
    </div>

    <div class="navbar-menu">
      <div class="navbar-start">
        <a
          class="navbar-item px-2"
          target="_blank"
          href="https://docs.case.app"
        >
          <span class="is-flex is-align-items-center is-justify-content-center">
            <span>Docs</span>
            <span class="icon ml-1">
              <i
                class="fa-solid fa-square-up-right"
                style="position: relative; top: -2px"
              ></i>
            </span>
          </span>
        </a>
        <a class="navbar-item px-2" routerLink="/faq">
          <span>FAQ</span>
        </a>
      </div>
      <div class="navbar-end">
        <div class="navbar-item pt-2">
          <a
            class="github-button"
            href="https://github.com/casejs/case"
            data-icon="octicon-star"
            data-size="large"
            data-show-count="true"
            aria-label="Star casejs/case on GitHub"
            >Star</a
          >
        </div>
        <a
          class="navbar-item px-2"
          href="https://discord.com/invite/FepAked3W7"
          target="_blank"
        >
          <i class="fa-brands fa-discord"></i>
        </a>
        <div class="navbar-item">
          <a
            class="button is-success"
            href="https://docs.case.app"
            target="_blank"
          >
            Get started
          </a>
        </div>
        <div class="navbar-item pl-0">
          <div class="dropdown is-active">
            <div class="dropdown-trigger">
              <button
                class="button is-danger"
                aria-haspopup="true"
                aria-controls="dropdown-menu"
                (click)="isDemoMenuOpen = !isDemoMenuOpen"
              >
                <span class="icon is-small">
                  <i class="fa-solid fa-desktop" aria-hidden="true"></i>
                </span>
                <span>Live demo</span>
                <span class="icon is-small">
                  <i class="fas fa-angle-down" aria-hidden="true"></i>
                </span>
              </button>
            </div>
            <div
              class="dropdown-menu"
              id="dropdown-menu"
              role="menu"
              *ngIf="isDemoMenuOpen"
            >
              <div class="dropdown-content">
                <a
                  class="dropdown-item has-text-dark"
                  target="_blank"
                  href="https://demo2.case.app/auth/login?email=user1@case.app&password=case"
                >
                  Invoicing app
                </a>
                <a
                  target="_blank"
                  href="https://demo3.case.app/auth/login?email=user1@case.app&password=case"
                  class="dropdown-item has-text-dark"
                >
                  Project management app
                </a>
                <a
                  target="_blank"
                  href="https://demo1.case.app/auth/login?email=user1@case.app&password=case"
                  class="dropdown-item has-text-dark"
                >
                  HR dashboard
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>
`

// src/app/components/layout/Header.tsx
// components/Header.js

const Header = () => {
  return (
    <nav
      className="navbar has-background-glass is-fixed-top"
      role="navigation"
      aria-label="main navigation"
    >
      <div className="container">
        <div className="navbar-brand">
          <a className="navbar-item" href="/">
            <img
              src="/assets/images/logo-poc.svg"
              width={198}
              alt="logo of manifest"
              loading="lazy"
              className="mx-2"
            />
          </a>
          <div className="is-flex">
            <a
              className="navbar-item px-5-tablet is-hidden-mobile"
              href="/playground"
            >
              <span className="is-hidden-touch">Playground</span>
              <i className="fa-solid fa-bolt is-size-6 is-hidden-desktop"></i>
            </a>
            <a className="navbar-item px-5-tablet" href="/docs" target="_blank">
              <span className="is-hidden-touch mr-2">Documentation</span>
              <i className="fa-solid fa-arrow-up-right-from-square content is-small is-hidden-touch mb-0"></i>
              <i className="lni lni-empty-file is-size-6 is-hidden-desktop"></i>
            </a>
            <a
              className="navbar-item px-5-tablet is-hidden-desktop"
              href="https://discord.gg/FepAked3W7"
              target="_blank"
            >
              <i className="lni lni-discord-alt is-size-6"></i>
            </a>
            <a
              className="navbar-item px-5-tablet is-hidden-desktop"
              href="https://github.com/mnfst/manifest"
              target="_blank"
            >
              <i className="lni lni-github-original is-size-6"></i>
            </a>
          </div>
        </div>

        <div className="navbar-menu has-text-weight-bold">
          <div className="navbar-end">
            <a
              className="navbar-item"
              href="https://discord.gg/FepAked3W7"
              target="_blank"
            >
              <i className="lni lni-discord-alt is-size-6"></i>
            </a>
            <a
              className="navbar-item"
              href="https://github.com/mnfst/manifest"
              target="_blank"
            >
              <i className="lni lni-github-original is-size-6"></i>
            </a>
            <div className="navbar-item">
              <a
                className="button is-small is-link"
                href="/docs/install"
                target="_blank"
              >
                Get started
              </a>
            </div>
          </div>
        </div>
      </div>
    </nav>
  )
}

export default Header
