// client/src/app/modules/website/pages/faq/faq.component.ts
import { NgClass, NgFor } from '@angular/common'
import { Component } from '@angular/core'

@Component({
  selector: 'app-faq',
  standalone: true,
  imports: [NgFor, NgClass],
  templateUrl: './faq.component.html',
  styleUrl: './faq.component.scss'
})
export class FaqComponent {
  selectedFaqIndex: number = -1
  faqItems: { question: string; answer: string }[] = [
    {
      question: 'Is Manifest a low-code / no-code tool ?',
      answer:
        "No. It just works like just any other file in your codebase. It's code, simple code."
    },
    {
      question: 'Is Manifest for me?',
      answer:
        'It does not matter if you are junior or senior developer, if you code in JS, PHP or Python. You can be frontend, backend or fullstack, a mobile developer, indie hacker or devsigner. If you know a bit of software development, you will have no problem using Manifest.'
    },
    {
      question: 'Can I use Manifest in production?',
      answer:
        'Manifest is currently in BETA, you can use it at your own risk. It is stable enough to power small projects, prototypes and MVPs but we do not recommend to use it on critical platforms.'
    },
    {
      question: 'What is behind the magic?',
      answer:
        'Good sense and ordinary popular stacks: the current version runs on NodeJS, Express and NestJS. We use JSON Schema to validate the YAML file, JS-YAML to parse it and TypeORM to map it into a SQLite database.'
    }
  ]

  toggleFaq(index: number) {
    if (this.selectedFaqIndex === index) {
      this.selectedFaqIndex = -1
    } else {
      this.selectedFaqIndex = index
    }
  }
}

<div class="container-fluid mt-6 pt-4 mb-6">
  <div class="container zi-1">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <div class="content">
          <h1 class="title is-2">FAQ</h1>

          <div
            *ngFor="let faqItem of faqItems; let index = index"
            class="card is-shadowless faq-item mb-4 has-background-white"
          >
            <a
              (click)="toggleFaq(index)"
              class="faq-question has-text-dark is-flex is-justify-content-space-between is-align-items-center"
            >
              <h4 class="mb-0">{{ faqItem.question }}</h4>
              <i
                class="lni"
                [ngClass]="{
                  'lni-chevron-up': selectedFaqIndex === index,
                  'lni-chevron-down': selectedFaqIndex !== index
                }"
              ></i>
            </a>
            <div
              class="faq-answer"
              [ngClass]="{
                visible: selectedFaqIndex === index,
                hidden: selectedFaqIndex !== index
              }"
            >
              <p *ngFor="let paragraph of faqItem.answer">{{ paragraph }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// src/app/components/FAQ.tsx
'use client'

import React, { useEffect, useRef, useState } from 'react'
import './FAQ.scss'

type FAQItem = {
  question: string
  answer: string
}

export const FAQ: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null)
  const contentRefs = useRef<Array<HTMLDivElement | null>>([])

  const faqs: FAQItem[] = [
    {
      question: 'Is Manifest a low-code / no-code tool ?',
      answer:
        "No. It just works like just any other file in your codebase. It's code, simple code."
    },
    {
      question: 'Is Manifest for me?',
      answer:
        'It does not matter if you are junior or senior developer, if you code in JS, PHP or Python. You can be frontend, backend or fullstack, a mobile developer, indie hacker or devsigner. If you know a bit of software development, you will have no problem using Manifest.'
    },
    {
      question: 'Can I use Manifest in production?',
      answer:
        'Manifest is currently in BETA, you can use it at your own risk. It is stable enough to power small projects, prototypes and MVPs but we do not recommend to use it on critical platforms.'
    },
    {
      question: 'What is behind the magic?',
      answer:
        'Good sense and ordinary popular stacks: the current version runs on NodeJS, Express and NestJS. We use JSON Schema to validate the YAML file, JS-YAML to parse it and TypeORM to map it into a SQLite database.'
    }
  ]

  const toggleFAQ = (index: number) => {
    setOpenIndex(index === openIndex ? null : index)
  }

  useEffect(() => {
    contentRefs.current.forEach((content, index) => {
      if (content) {
        content.style.height =
          openIndex === index ? `${content.scrollHeight}px` : '0px'
      }
    })
  }, [openIndex])

  return (
    <div className="content">
      <div className="has-text-centered">
        <h2 className="mb-6">FAQ</h2>
      </div>
      {faqs.map((faq, index) => (
        <div
          key={index}
          className="card is-shadowless faq-item mb-4 has-background-white-bis"
        >
          <a
            onClick={() => toggleFAQ(index)}
            aria-expanded={openIndex === index}
            aria-controls={`faq-content-${index}`}
            className="faq-question has-text-dark is-flex is-justify-content-space-between is-align-items-center"
          >
            <h4 className="mb-0">{faq.question}</h4>
            <i
              className={`lni ${
                openIndex === index ? 'lni-chevron-up' : 'lni-chevron-down'
              }`}
            ></i>
          </a>
          <div
            id={`faq-content-${index}`}
            ref={(el) => (contentRefs.current[index] = el)}
            className="faq-answer"
            style={{
              overflow: 'hidden',
              transition: 'height 0.3s ease-in-out'
            }}
          >
            <p>{faq.answer}</p>
          </div>
        </div>
      ))}
    </div>
  )
}
